global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
    metrics_path: '/metrics'

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8002']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8003']
    metrics_path: '/metrics'

  - job_name: 'ai-engine'
    static_configs:
      - targets: ['ai-engine:8004']
    metrics_path: '/metrics'

  - job_name: 'event-store'
    static_configs:
      - targets: ['event-store:8005']
    metrics_path: '/metrics'
