# External Secrets Operator Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: aic-platform
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: aic-platform
spec:
  provider:
    azurekv:
      vaultUrl: "https://aic-keyvault.vault.azure.net/"
      authType: ServicePrincipal
      serviceAccountRef:
        name: azure-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: aic-platform
spec:
  provider:
    gcpsm:
      projectId: "aic-enterprise-platform"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: aic-cluster
          serviceAccountRef:
            name: gcp-secrets-sa
---
# Database Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secrets
  namespace: aic-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}?sslmode=require"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DB_NAME: "{{ .database }}"
  data:
  - secretKey: username
    remoteRef:
      key: aic/database/production
      property: username
  - secretKey: password
    remoteRef:
      key: aic/database/production
      property: password
  - secretKey: host
    remoteRef:
      key: aic/database/production
      property: host
  - secretKey: port
    remoteRef:
      key: aic/database/production
      property: port
  - secretKey: database
    remoteRef:
      key: aic/database/production
      property: database
---
# API Keys and JWT Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: aic-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-credentials
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: aic/api/production
      property: jwt_secret
  - secretKey: API_KEY
    remoteRef:
      key: aic/api/production
      property: api_key
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: aic/api/production
      property: encryption_key
  - secretKey: OAUTH_CLIENT_SECRET
    remoteRef:
      key: aic/oauth/production
      property: client_secret
---
# AI/ML Service Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-secrets
  namespace: aic-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ai-credentials
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: aic/ai/production
      property: openai_key
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: aic/ai/production
      property: anthropic_key
  - secretKey: VECTOR_DB_TOKEN
    remoteRef:
      key: aic/ai/production
      property: vector_db_token
