apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: security
  labels:
    app: keycloak
    part-of: aic-website
type: Opaque
stringData:
  admin-password: "changeme"  # Change this in production

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-database-credentials
  namespace: security
  labels:
    app: keycloak
    part-of: aic-website
type: Opaque
stringData:
  admin-password: "changeme"  # Change this in production
  user-password: "changeme"   # Change this in production
  replication-password: "changeme"  # Change this in production

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: security
  labels:
    app: keycloak
    part-of: aic-website
type: Opaque
stringData:
  aic-website-frontend: "changeme"  # Change this in production
  aic-website-backend-api: "changeme"  # Change this in production
  aic-website-ai-services: "changeme"  # Change this in production
  kong-api-gateway: "changeme"  # Change this in production

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-ldap-credentials
  namespace: security
  labels:
    app: keycloak
    part-of: aic-website
type: Opaque
stringData:
  bind-password: "changeme"  # Change this in production

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-smtp-credentials
  namespace: security
  labels:
    app: keycloak
    part-of: aic-website
type: Opaque
stringData:
  smtp-password: "changeme"  # Change this in production
