apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/applied-innovation-corp/aic-website.git
    targetRevision: main
    path: kubernetes/services/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
