apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: cms
  labels:
    app: ghost-cms
    part-of: aic-website
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
