apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-auth
  namespace: api-gateway
  labels:
    app: kong
    part-of: aic-website
config:
  client_id: kong-api-gateway
  client_secret:
    valueFrom:
      secretKeyRef:
        name: keycloak-client-secrets
        key: kong-api-gateway
  discovery: https://auth.example.com/realms/aic-website/.well-known/openid-configuration
  introspection_endpoint: https://auth.example.com/realms/aic-website/protocol/openid-connect/token/introspect
  bearer_only: "yes"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - kong-api-gateway
    - aic-website-backend-api
    - aic-website-ai-services
  ssl_verify: "no"
  timeout: 10000
  introspection_cache_ignore: "no"
  introspection_expiry: 60
  token_endpoint_auth_method: client_secret_post
  filters: null
  scopes: null
plugin: oidc

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-auth-frontend
  namespace: api-gateway
  labels:
    app: kong
    part-of: aic-website
config:
  client_id: aic-website-frontend
  client_secret:
    valueFrom:
      secretKeyRef:
        name: keycloak-client-secrets
        key: aic-website-frontend
  discovery: https://auth.example.com/realms/aic-website/.well-known/openid-configuration
  introspection_endpoint: https://auth.example.com/realms/aic-website/protocol/openid-connect/token/introspect
  bearer_only: "no"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - aic-website-frontend
  ssl_verify: "no"
  timeout: 10000
  introspection_cache_ignore: "no"
  introspection_expiry: 60
  token_endpoint_auth_method: client_secret_post
  login_redirect_uri: https://www.example.com/auth/callback
  logout_redirect_uri: https://www.example.com/
  login_redirect_mode: query
  forbidden_redirect_uri: https://www.example.com/forbidden
  unauthorized_redirect_uri: https://www.example.com/login
  filters: null
  scopes:
    - openid
    - profile
    - email
plugin: oidc

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-keycloak
  namespace: api-gateway
  labels:
    app: kong
    part-of: aic-website
config:
  origins:
    - https://www.example.com
    - https://staging.example.com
    - https://dev.example.com
    - https://auth.example.com
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - HEAD
  headers:
    - Authorization
    - Content-Type
    - Accept
    - Origin
    - User-Agent
    - DNT
    - Cache-Control
    - X-Mx-ReqToken
    - Keep-Alive
    - X-Requested-With
    - If-Modified-Since
  exposed_headers:
    - Authorization
    - Content-Type
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors
