apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: observability
  labels:
    app: elasticsearch
    part-of: aic-website
type: Opaque
stringData:
  # These are example passwords - in production, use a proper secret management solution
  password: "changeme"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-credentials
  namespace: observability
  labels:
    app: kibana
    part-of: aic-website
type: Opaque
stringData:
  # These are example passwords - in production, use a proper secret management solution
  password: "changeme"
  encryptionKey: "a-very-long-and-secure-encryption-key-at-least-32-characters"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-credentials
  namespace: observability
  labels:
    app: logstash
    part-of: aic-website
type: Opaque
stringData:
  # These are example passwords - in production, use a proper secret management solution
  password: "changeme"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-s3-credentials
  namespace: observability
  labels:
    app: elasticsearch
    part-of: aic-website
type: Opaque
stringData:
  # These are example credentials - in production, use a proper secret management solution
  s3.client.default.access_key: "AKIAIOSFODNN7EXAMPLE"
  s3.client.default.secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
