global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics

  - job_name: 'kuma-dataplanes'
    static_configs:
      - targets: ['kuma-control-plane:5676']
    metrics_path: /metrics

  - job_name: 'kuma-control-plane'
    static_configs:
      - targets: ['kuma-control-plane:5681']
    metrics_path: /metrics
