apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: aic-mesh
metadata:
  name: allow-all-traffic
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'
