apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-models-cache
  namespace: ai-services
  labels:
    app: ai-services
    part-of: aic-website
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
