apiVersion: v1
kind: Service
metadata:
  name: ai-services
  namespace: ai-services
  labels:
    app: ai-services
    part-of: aic-website
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ai-services
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
