apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-config
  namespace: backend-services
  labels:
    app: backend-api
    part-of: aic-website
data:
  app-config.json: |
    {
      "api": {
        "version": "v1",
        "rateLimit": {
          "windowMs": 900000,
          "max": 100
        },
        "cors": {
          "allowedOrigins": ["https://www.example.com", "https://admin.example.com"],
          "allowedMethods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
          "allowedHeaders": ["Content-Type", "Authorization"],
          "exposedHeaders": ["X-Request-ID"],
          "maxAge": 86400
        }
      },
      "logging": {
        "level": "info",
        "format": "json",
        "requestLogging": true
      },
      "cache": {
        "ttl": 300,
        "checkPeriod": 60
      },
      "kafka": {
        "topics": {
          "userEvents": "user-events",
          "notifications": "notifications",
          "analytics": "analytics"
        },
        "consumerGroup": "backend-api"
      }
    }
  
  feature-flags.json: |
    {
      "enableNewUserFlow": true,
      "enableAnalytics": true,
      "enableCaching": true,
      "enableRateLimiting": true
    }
