# Namespace with Resource Quotas and Network Policies
apiVersion: v1
kind: Namespace
metadata:
  name: aic-platform
  labels:
    name: aic-platform
    security.policy: restricted
    network.policy: enabled
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aic-platform-quota
  namespace: aic-platform
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "50"
    configmaps: "50"
    pods: "100"
---
# Limit Range for default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: aic-platform-limits
  namespace: aic-platform
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
---
# Network Policy - Default Deny All
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: aic-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Network Policy - Allow Internal Communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: aic-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: aic-platform
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: aic-platform
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
